### ISSUE TITLE
弹幕墙链接失效

### ISSUE THREAD

**Issue by yukiSolo** [FreeCodeCampChina/freecodecamp.cn#35]
Challenge [Design a danmu app](https://www.freecodecamp.cn/challenges/design-a-danmu-app) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![default](https://cloud.githubusercontent.com/assets/22395006/19793267/9459dd2e-9cfe-11e6-8510-76cdcee48bca.jpg)

**Comment by jamesbeme** [comment]
S T O P.  ALL. EMAILS.  S T O P!

On Oct 27, 2016 10:06 PM, "夏胤" notifications@github.com wrote:

Challenge Design a danmu app
https://www.freecodecamp.cn/challenges/design-a-danmu-app has an issue.
User Agent is: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36.
Please describe how to reproduce this issue, and include links to
screenshots if possible.
[image: default]
https://cloud.githubusercontent.com/assets/22395006/19793267/9459dd2e-9cfe-11e6-8510-76cdcee48bca.jpg

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/FreeCodeCampChina/freecodecamp.cn/issues/35, or mute
the thread

**Comment by discountry** [comment]
已修复
