### ISSUE TITLE
I find a  bug in Smallest Common Multiple

### ISSUE THREAD

**Issue by gdccwxx** [FreeCodeCampChina/freecodecamp.cn#480]
#### FreeCodeCamp.cn Issue 模板
如何使用本模板:
* 尽可能多填些相关信息，方便管理员参考
* 对于无法给出的内容，请删除掉那一行

# 以上内容请在提交 Issue 之前删除

#### 浏览器信息
* 浏览器名称，版本号
* 操作系统

#### 问题描述
* 问题是在什么时候，什么情况下遇到的
* 简要说明如何重现

#### 你的代码

```
如果和代码相关，请在这里粘贴你的全部代码
```

#### 截图（如果有）

you can see,the smallest common myltiple[1,5] is 5,if my math not bad..but the answer is 60,maybe the question not [1,5],is [12, 5]i think..
i'm one of person who like the web, so... may it's can help you

**Comment by S1ngS1ng** [comment]
@gdccwxx 
# PLEASE DO ME A FAVOR
- Next time when you open an issue/pr, please make sure that you've **READ THROUGH** the description/guideline (i.e. 以上内容请在提交 Issue 之前删除)

# As per your question (I'll reply inline)
> you can see, the smallest common myltiple[1,5] is 5

Sorry, it is not, where `[1, 5]` refers to `1, 2, 3, 4 and 5` instead of `1 and 5`

> i'm one of person who like the web, so... may it's can help you

Appreciate that. Good luck, have fun.
